name: sudoku
description: "A simple yet nice sudoku app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^9.3.0+1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  very_good_analysis: ^7.0.0

dev_dependencies:
  auto_route_generator: ^9.3.1
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
