name: sudoku
description: "A simple yet nice sudoku app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^9.3.0+1
  bloc: ^8.1.4
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^9.1.5
  intl: any
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  pine: ^1.0.3
  provider: ^6.1.2
  rxdart: ^0.28.0
  sudoku_solver_generator: ^2.1.0+1
  very_good_analysis: ^7.0.0
  vibration: ^3.1.3

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: any
  data_fixture_dart: ^2.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4
  test: ^1.25.7

flutter:
  generate: true
  uses-material-design: true
